-- plugins/which-key.lua
-- 中文化 which-key 群組與常用 LazyVim 內建快捷鍵說明

return {
  {
    "folke/which-key.nvim",
    opts = {
      spec = {
        -- Leader 主群組
        { "<leader>b", group = "Buffer 管理" },
        { "<leader>c", group = "程式碼 / LSP" },
        { "<leader>d", group = "除錯 / Profiler" },
        { "<leader>f", group = "檔案 / 搜尋" },
        { "<leader>g", group = "Git" },
        { "<leader>h", group = "Flash 跳轉" },
        { "<leader>m", group = "Markdown" },
        { "<leader>q", group = "Session / 離開" },
        { "<leader>s", group = "搜尋 / 系統工具" },
        { "<leader>sn", group = "Noice 訊息" },
        { "<leader>t", group = "終端機" },
        { "<leader>o", group = "其他 / Neo-tree" },
        { "<leader>u", group = "UI 切換" },
        { "<leader>w", group = "視窗" },
        { "<leader>x", group = "診斷 / Trouble" },
        { "<leader><Tab>", group = "分頁 Tab" },

        -- 常用 LazyVim 內建說明覆寫
        { "<leader><space>", desc = "搜尋檔案（專案根目錄）" },
        { "<leader>,", desc = "切換 Buffer" },
        { "<leader>/", desc = "全文搜尋（專案根目錄）" },
        { "<leader>:", desc = "命令歷史" },
        { "<leader>`", desc = "切換上一個 Buffer" },
        { "<leader>?", desc = "顯示目前 Buffer 快捷鍵" },

        { "<leader>bb", desc = "切換上一個 Buffer" },
        { "<leader>bd", desc = "刪除 Buffer" },
        { "<leader>bD", desc = "刪除 Buffer 和視窗" },
        { "<leader>bo", desc = "刪除其他 Buffer" },
        { "<leader>bp", desc = "釘選 / 取消釘選 Buffer" },

        { "<leader>ca", desc = "程式碼動作" },
        { "<leader>cd", desc = "顯示本行診斷" },
        { "<leader>cf", desc = "格式化" },
        { "<leader>cF", desc = "格式化嵌入語言" },
        { "<leader>cm", desc = "開啟 Mason" },
        { "<leader>cr", desc = "重新命名符號" },
        { "<leader>cs", desc = "符號清單（Trouble）" },
        { "<leader>cS", desc = "LSP 參考 / 定義（Trouble）" },

        { "<leader>e", desc = "Snacks Explorer（專案根目錄）" },
        { "<leader>E", desc = "Snacks Explorer（目前工作目錄）" },
        { "<leader>oe", desc = "切換 Neo-tree" },
        { "<leader>oE", desc = "Neo-tree 顯示目前檔案" },
        { "<leader>fn", desc = "新增檔案" },
        { "<leader>fF", desc = "搜尋檔案（目前目錄）" },
        { "<leader>fR", desc = "最近檔案（目前目錄）" },

        { "<leader>gg", desc = "Lazygit（專案根目錄）" },
        { "<leader>gG", desc = "Lazygit（目前目錄）" },
        { "<leader>gb", desc = "Git blame 目前行" },
        { "<leader>gd", desc = "Git diff hunks" },
        { "<leader>gD", desc = "Git diff origin" },
        { "<leader>gf", desc = "目前檔案 Git 歷史" },
        { "<leader>gl", desc = "Git log" },
        { "<leader>gL", desc = "Git log（目前目錄）" },
        { "<leader>gs", desc = "Git 狀態" },
        { "<leader>gS", desc = "Git stash" },

        { "<leader>qs", desc = "還原 Session" },
        { "<leader>ql", desc = "還原上一個 Session" },
        { "<leader>qS", desc = "選擇 Session" },
        { "<leader>qd", desc = "目前 Session 不儲存" },
        { "<leader>qq", desc = "全部退出" },

        { "<leader>sg", desc = "全文搜尋（專案根目錄）" },
        { "<leader>sG", desc = "全文搜尋（目前目錄）" },
        { "<leader>sb", desc = "搜尋目前 Buffer 行" },
        { "<leader>sB", desc = "搜尋所有開啟 Buffer" },
        { "<leader>sd", desc = "搜尋診斷" },
        { "<leader>sD", desc = "搜尋本 Buffer 診斷" },
        { "<leader>sh", desc = "搜尋說明文件" },
        { "<leader>sk", desc = "搜尋快捷鍵" },
        { "<leader>sr", desc = "搜尋與取代" },
        { "<leader>sR", desc = "恢復上次搜尋" },
        { "<leader>sw", desc = "搜尋游標文字（根目錄）" },
        { "<leader>sW", desc = "搜尋游標文字（目前目錄）" },
        { "<leader>snl", desc = "上一則 Noice 訊息" },
        { "<leader>snh", desc = "Noice 訊息歷史" },
        { "<leader>sna", desc = "全部 Noice 訊息" },
        { "<leader>snd", desc = "關閉所有 Noice 訊息" },

        { "<leader>ud", desc = "切換診斷顯示" },
        { "<leader>uf", desc = "切換自動格式化（全域）" },
        { "<leader>uF", desc = "切換自動格式化（Buffer）" },
        { "<leader>uh", desc = "切換 Inlay Hints" },
        { "<leader>ul", desc = "切換行號" },
        { "<leader>uL", desc = "切換相對行號" },
        { "<leader>us", desc = "切換拼字檢查" },
        { "<leader>uw", desc = "切換自動換行" },

        { "<leader>xx", desc = "診斷清單（Trouble）" },
        { "<leader>xX", desc = "目前 Buffer 診斷（Trouble）" },
        { "<leader>xq", desc = "Quickfix 清單（Trouble）" },
        { "<leader>xl", desc = "Location 清單（Trouble）" },
        { "<leader>xt", desc = "Todo 清單（Trouble）" },
        { "<leader>xT", desc = "Todo / Fix / FIXME（Trouble）" },
      },
    },
  },
}
